# Generated by Django 4.1.7 on 2023-05-17 13:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(blank=True, null=True)),
                ('username', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='用户名')),
                ('password', models.CharField(default='123456', max_length=255, verbose_name='密码')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('nickname', models.CharField(blank=True, max_length=255, verbose_name='昵称')),
                ('role', models.CharField(choices=[('visitor', '访客'), ('user', '用户'), ('admin', '管理员')], default='visitor', max_length=20, verbose_name='角色')),
                ('experience', models.IntegerField(default=0, verbose_name='经验值')),
                ('level', models.IntegerField(default=1, verbose_name='等级')),
                ('register_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='头像')),
                ('signature', models.CharField(blank=True, max_length=255, verbose_name='个性签名')),
                ('telephone', models.CharField(blank=True, default='12345678910', max_length=11, verbose_name='手机号')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='资源名称')),
                ('author', models.CharField(max_length=255, verbose_name='作者')),
                ('description', models.TextField(verbose_name='资源描述')),
                ('filetype', models.CharField(default='其他', max_length=255, verbose_name='资源文件分类')),
                ('subject', models.CharField(default='其他', max_length=255, verbose_name='资源学科')),
                ('file', models.FileField(upload_to='resources/', verbose_name='文件')),
                ('file_url', models.URLField(verbose_name='文件链接')),
                ('download_count', models.IntegerField(default=0, verbose_name='下载次数')),
                ('upload_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上传时间')),
                ('user', models.ForeignKey(blank=True, db_column='username', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'verbose_name': 'resource',
                'verbose_name_plural': 'resources',
                'db_table': 'resource',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='帖子标题')),
                ('content', models.TextField(verbose_name='帖子内容')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('like_count', models.IntegerField(default=0, verbose_name='点赞次数')),
                ('comment_count', models.IntegerField(default=0, verbose_name='评论次数')),
                ('require_level', models.IntegerField(default=1, verbose_name='要求等级')),
                ('user', models.ForeignKey(blank=True, db_column='username', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
                'db_table': 'post',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', '登录'), ('post', '发帖'), ('comment', '评论'), ('like', '点赞')], max_length=20, verbose_name='动作')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='时间戳')),
                ('user', models.ForeignKey(blank=True, db_column='username', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'verbose_name': 'log',
                'verbose_name_plural': 'logs',
                'db_table': 'log',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('comment_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='评论时间')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.post')),
                ('user', models.ForeignKey(blank=True, db_column='username', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
                'db_table': 'comment',
            },
        ),
    ]
