# Generated by Django 4.1.7 on 2023-05-25 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExceptionComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(blank=True, db_column='username', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user')),
                ('comment_id', models.ForeignKey(blank=True, db_column='comment_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.comment_for_post')),
            ],
            options={
                'db_table': 'exception_comment',
            },
        ),
    ]
