# Generated by Django 4.1.7 on 2023-05-16 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telephone',
            field=models.CharField(blank=True, default='12345678910', max_length=11, verbose_name='手机号'),
        ),
    ]
