# Generated by Django 4.1.7 on 2023-05-21 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_role_admin_requst'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin_requst',
            new_name='Admin_request',
        ),
    ]
