# Generated by Django 4.1.7 on 2023-05-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_telephone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='category',
        ),
        migrations.AddField(
            model_name='resource',
            name='filetype',
            field=models.CharField(default='其他', max_length=255, verbose_name='资源文件分类'),
        ),
        migrations.AddField(
            model_name='resource',
            name='subject',
            field=models.CharField(default='其他', max_length=255, verbose_name='资源学科'),
        ),
        migrations.AlterModelTable(
            name='comment',
            table='comment',
        ),
        migrations.AlterModelTable(
            name='log',
            table='log',
        ),
        migrations.AlterModelTable(
            name='post',
            table='post',
        ),
        migrations.AlterModelTable(
            name='resource',
            table='resource',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
