# Generated by Django 4.1.7 on 2023-06-05 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_exceptioncomment_exception_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='likenotice',
            name='doer',
            field=models.ForeignKey(blank=True, db_column='doer', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes_given', to='user.user'),
        ),
        migrations.AlterField(
            model_name='likenotice',
            name='user',
            field=models.ForeignKey(blank=True, db_column='username', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_received', to='user.user'),
        ),
    ]
