# Generated by Django 4.1.7 on 2023-05-17 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_post_post_time_post_update_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='require_level',
            field=models.IntegerField(default=1, verbose_name='要求等级'),
        ),
    ]
