# Generated by Django 4.1.7 on 2023-05-18 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_exceptionlog_flavorpost_flavorresource_delete_log'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExceptionLog',
            new_name='ExceptionUser',
        ),
        migrations.AddField(
            model_name='resource',
            name='report_count',
            field=models.IntegerField(default=0, verbose_name='举报次数'),
        ),
        migrations.CreateModel(
            name='ExceptionResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(blank=True, db_column='username', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
