# Generated by Django 4.1.7 on 2023-05-18 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_user_last_login'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exceptionuser',
            options={},
        ),
        migrations.AlterModelOptions(
            name='flavorpost',
            options={},
        ),
        migrations.AlterModelOptions(
            name='flavorresource',
            options={},
        ),
        migrations.AddField(
            model_name='comment',
            name='like_count',
            field=models.IntegerField(default=0, verbose_name='点赞次数'),
        ),
        migrations.AddField(
            model_name='comment',
            name='report_count',
            field=models.IntegerField(default=0, verbose_name='举报次数'),
        ),
        migrations.AddField(
            model_name='exceptionresource',
            name='exception_reason',
            field=models.TextField(default='无', verbose_name='异常原因'),
        ),
        migrations.AddField(
            model_name='exceptionresource',
            name='source_id',
            field=models.ForeignKey(blank=True, db_column='source_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.resource'),
        ),
        migrations.AddField(
            model_name='flavorpost',
            name='post_id',
            field=models.ForeignKey(blank=True, db_column='post_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.post'),
        ),
        migrations.AddField(
            model_name='flavorresource',
            name='resource_id',
            field=models.ForeignKey(blank=True, db_column='resource_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.resource'),
        ),
        migrations.AddField(
            model_name='post',
            name='report_count',
            field=models.IntegerField(default=0, verbose_name='举报次数'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_waring',
            field=models.BooleanField(default=False, verbose_name='是否被警告'),
        ),
        migrations.AlterField(
            model_name='flavorpost',
            name='flavor_title',
            field=models.TextField(default='无', verbose_name='倾向标题'),
        ),
        migrations.AlterField(
            model_name='flavorresource',
            name='flavor_title',
            field=models.TextField(default='无', verbose_name='倾向标题'),
        ),
        migrations.AlterModelTable(
            name='exceptionresource',
            table='exception_resource',
        ),
        migrations.CreateModel(
            name='ExceptionPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exception_reason', models.TextField(default='无', verbose_name='异常原因')),
                ('author', models.ForeignKey(blank=True, db_column='username', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user')),
                ('post_id', models.ForeignKey(blank=True, db_column='post_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.post')),
            ],
            options={
                'db_table': 'exception_post',
            },
        ),
    ]
